// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc2rc-rsWkWI2rr17NAIrDROVJOH1Mvkk',
    appId: '1:328841506268:web:6292a9ca4b2c42889bb319',
    messagingSenderId: '328841506268',
    projectId: 'minidocto',
    authDomain: 'minidocto.firebaseapp.com',
    storageBucket: 'minidocto.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0BiC-Tjo18FxOE11Q-VlHJy9xrqNJUFg',
    appId: '1:328841506268:android:c16120616f0a17789bb319',
    messagingSenderId: '328841506268',
    projectId: 'minidocto',
    storageBucket: 'minidocto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwlQr_21wdfk_QGqn_X-FWQ3fy6iLOLZg',
    appId: '1:328841506268:ios:d1d34ca8e043be859bb319',
    messagingSenderId: '328841506268',
    projectId: 'minidocto',
    storageBucket: 'minidocto.firebasestorage.app',
    iosBundleId: 'com.example.miniDocto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwlQr_21wdfk_QGqn_X-FWQ3fy6iLOLZg',
    appId: '1:328841506268:ios:d1d34ca8e043be859bb319',
    messagingSenderId: '328841506268',
    projectId: 'minidocto',
    storageBucket: 'minidocto.firebasestorage.app',
    iosBundleId: 'com.example.miniDocto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc2rc-rsWkWI2rr17NAIrDROVJOH1Mvkk',
    appId: '1:328841506268:web:6a0efbdb549f43a19bb319',
    messagingSenderId: '328841506268',
    projectId: 'minidocto',
    authDomain: 'minidocto.firebaseapp.com',
    storageBucket: 'minidocto.firebasestorage.app',
  );
}
